### ISSUE TITLE
[RFC] Coding conventions - pylint configuration

### ISSUE THREAD

**Issue by fcatalan92** [hipe4ml/hipe4ml#10]
Hi,
I think that it is a good idea to discuss the coding conventions as soon as possible. The current configuration of pylint is this one:
```
[FORMAT]
indent-string='    '
max-line-length=120

[BASIC]
function-naming-style=camelCase
argument-naming-style=camelCase
variable-naming-style=camelCase
method-naming-style=camelCase
attr-naming-style=camelCase

[MESSAGES CONTROL]
disable=useless-object-inheritance

[DESIGN]
max-args=10
max-locals=40
```
@hipe4ml/developers Do you have any change to propose?

We can also start to write some code and see how this configuration feels, but I would try to not wait too much and then have to change a lot of code.

**Comment by fmazzasc** [comment]
The current code in the Hypertriton repository is written using the snake_case convention. Do you have any reason to prefer the CamelCase one?

**Comment by fgrosa** [comment]
Personally I do not have preferences and if you already have the code written with the snake_case convention, it is fine for me to change it.

**Comment by mconcas** [comment]
Just to wrap it up:

<p><a href="https://api.gh-polls.com/poll/01DTKYBHTBB2HABGWNHSH640J9/camelCase/vote"><img src="https://api.gh-polls.com/poll/01DTKYBHTBB2HABGWNHSH640J9/camelCase" alt=""></a>
<a href="https://api.gh-polls.com/poll/01DTKYBHTBB2HABGWNHSH640J9/snake_case/vote"><img src="https://api.gh-polls.com/poll/01DTKYBHTBB2HABGWNHSH640J9/snake_case" alt=""></a></p>
