### ISSUE TITLE
Colab tutorial tree handler issue

### ISSUE THREAD

**Issue by shahidzk1** [hipe4ml/hipe4ml#109]
When I try to a upload a root file through tree handler on your google colab tutorial, the following error appears

AttributeError: 'Model_TTree_v20' object has no attribute 'pandas'

![Screenshot from 2021-01-14 13-33-31](https://user-images.githubusercontent.com/47216877/104591549-22c9b300-566d-11eb-9ae9-aac9a6fbe312.png)

**Comment by mconcas** [comment]
Dear @shahidzk1,
thanks for the feedback, we are working on that.
For the time being may I ask you to restart the runtime?
This should work.

Best

**Comment by shahidzk1** [comment]
Thanks for your reply Matteo Concas. It works now! Andrea dubla gave us insights to this code. If you don't mind shall I contact you through an email? My email address is shahidzafarkhan@gmail.com

**Comment by mconcas** [comment]
Hi, your email has been forwarded to hipe4ml@googlegroup.com mailing list.
