### ISSUE TITLE
Move to Uproot4 

### ISSUE THREAD

**Issue by fcatalan92** [hipe4ml/hipe4ml#116]
It would be nice to move to uproot 4 https://github.com/scikit-hep/uproot4. However, for the moment, it does not support writing root files. So, we should drop https://github.com/hipe4ml/hipe4ml/blob/9903f1cd743e42ad07a7e4bc94a825711f67fd65/hipe4ml/tree_handler.py#L430
Or we can wait until this feature is supported again https://github.com/scikit-hep/uproot4/issues/25

**Comment by fmazzasc** [comment]
I think we can drop the method and move to uproot4. I would not stop the migration for this minor (at least for LF-analyses) feature. @fcatalan92 what do you think?

**Comment by fcatalan92** [comment]
We are not using this functionality in HF analyses. So probably we can drop it (at least for the moment)
