### ISSUE TITLE
Error in the documentation of tree_handler.get_handler_from_large_file

### ISSUE THREAD

**Issue by danielbattistini** [hipe4ml/hipe4ml#123]
These lines do not match the function definition since there is no return value.

https://github.com/hipe4ml/hipe4ml/blob/3d21c7ba1cd7ec5be94f2530d31ef75696a6eaec/hipe4ml/tree_handler.py#L118-L121

**Comment by fmazzasc** [comment]
Thanks for spotting it @danielbattistini !
