### ISSUE TITLE
Warning while plotting variable distributions and precision-recall curve

### ISSUE THREAD

**Issue by mfaggin** [hipe4ml/hipe4ml#30]
Dear developers,

when plotting the variable distributions, it seems that the legenda are not plotted and the code returns this warning: 
```
No handles with labels found to put in legend.
Source ID 8 was not found when attempting to remove it
```
The first line appears also when plotting the precision-recall curve

I hope it can help.
Cheers.

**Comment by mpuccio** [comment]
Fixed with #35
