### ISSUE TITLE
A couple of possible ideas

### ISSUE THREAD

**Issue by mfaggin** [hipe4ml/hipe4ml#31]
Dear developers,
I tried your package and I would like to propose a couple of small fixes/ideas to improve it. Please, take them as humble suggestions coming from a dummy user, who tried the package just once:

1. the BDT score distributions for the training and testing samples are plotted without normalising them by the number of entries, maybe you can consider to add this option

2. you can consider to add a function that plots the learning curves (this should be a useful tool to see the model convergence) and another one that plots the ROC curves for both training and testing sample (to further keep overtraining under control; this would maybe help in case of binary classification).

Cheers.

**Comment by mpuccio** [comment]
Fixed by #36
