### ISSUE TITLE
returned type in plot_distr

### ISSUE THREAD

**Issue by pfecchio** [hipe4ml/hipe4ml#61]
In `plot_utils.plot_distr()` the returned object type should be `numpy` array of `matplotlib.figure.Figure` according to the function documentation. Instead I get `numpy` array of  `AxesSubplot` objects. We must update the function reference or change the returned object if it is convenient to use `matplotlib.figure.Figure`.

**Comment by fmazzasc** [comment]
Ciao @pfecchio ,
I'm working on it!

**Comment by fgrosa** [comment]
> Ciao @pfecchio ,
> I'm working on it!

@fmazzasc initially the method returned a ```matplotlib.figure.Figure```, but it was empty because the ```pands.DataFrame.hist``` function puts the histos in a ```AxesSubplot``` object instead of a ```matplotlib.figure.Figure```. IMHO we can stay with the ```AxesSubplot``` and change the docstring, but if you find a solution to return a ```matplotlib.figure.Figure``` is also fine

**Comment by fmazzasc** [comment]
done in #63
