### ISSUE TITLE
Provide complete sampling reproducibility for subsets in TreeHandler

### ISSUE THREAD

**Issue by pfecchio** [hipe4ml/hipe4ml#70]
Looking into the new **TreeHandler** class, I found out that the `get_subset()` method does not allow to pass on to the underlying `shuffle_data_frame()` any `**kwds`.

https://github.com/hipe4ml/hipe4ml/blob/e8a948cceb949f70184ea0b92de3faac9365d2c2/hipe4ml/tree_handler.py#L240

```python
def get_subset(self, selections=None, frac=None, size=None):
        ...


        ...

        subset = copy.copy(self)
        subset.deepcopy(self)

        if selections:
            subset.apply_preselections(selections, inplace=True)
        if frac or size:
            subset.shuffle_data_frame(frac=frac, size=size, inplace=True)
        return subset
```
Therefore it is not possible to provide the `random_state` argument to the `pandas.DataFrame.sample()` method (used in `shuffle_data_frame()`) and consequently the sampling reproducibility is not guaranteed. 

The sampling reproducibility is crucial for our analysis so I suggest to provide the possibility to pass `random_state` to `shuffle_data_frame()`. I already have an easy fix for this but I don't like it: https://github.com/pfecchio/hipe4ml/commit/3fcedc87a60a9bb16b431e81b193101a3393b5a7. 

A better solution would be to have `**kwds` for `get_subset()`,  passed on to `shuffle_data_frame()`. But in this case you should also provide `**kwds`,  for the `apply_preselection()` for the sake of completeness, and , as far as I know, it is not possible to have double `**kwds` argument in the same method. (Using the same `**kwds` argument for both `shuffle_data_frame()` and `apply_preselections()` can lead to compatibility problems, so I would not consider it)

Let me know what do you think about it (in particular @fmazzasc and @mpuccio who developed this class). If you have any suggestions about how to improve my patch, they are very welcome.

**Comment by fmazzasc** [comment]
Ciao @pfecchio , thanks for pointing out the issue. In my opinion for the purpose of this function there is no need to add` **kwds` since, except for the random state, I don't imagine a direct application of the [pandas.query](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.eval.html#pandas.eval) and [pandas.sample](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html?highlight=sample#pandas.DataFrame.sample) extra arguments in this case. Do you? If not I think that your quick solution is also the best one

**Comment by pfecchio** [comment]
Ciao @fmazzasc. I completely agree with you, I can't see a different application of the `**kwds` in this context, but I thought someone could have had different needs. So, I think I can open the PR for the patch. We will extend the funcitonalities if, in the future, other necessities arise.
