### ISSUE TITLE
unexpected behavior of installation from local source

### ISSUE THREAD

**Issue by pfecchio** [hipe4ml/hipe4ml#73]
While working on the tests I've found an unexpected and unwanted behavior of the installation from local source . When the package is installed with `pip install -e .` *hipe4ml* is not the only package installed, but also *examples* and *tests* packages are.

#### Reproduce the problem
You can see it by running `import examples.training_and_testing_example` in the python interpreter from any location on your machine. This should work only when the relative path for `examples.training_and_testing_example` is correct, instead it works from everywhere, as I've already shown to @fmazzasc. 

Conversely, the installation is correct when *hipe4ml* is installed from PyPI.

#### Possible explanation
I tried to figure out what's happening and it looks like we are installing a package for each directory in the base dir  which contains *.py* files and not only a package from **hipe4ml/** source.  This is due to the `find_packages()` method of *setuptools* which looks for *.py* files in all the directories in the base dir, then *setuptools* installs packages accordingly to the directories structure that `find_packages()` finds. See [setuptools page](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages).

#### Solution
I propose to switch to a **src/hipe4ml** schema to avoid this problem with the installation. (https://docs.pytest.org/en/latest/goodpractices.html) 
https://github.com/pfecchio/hipe4ml/commit/cf855dda0658996f43cba42a9f600c8a6528edac implements it by:

- creating **src** directory and moving **hipe4ml** -> **src/hipe4ml**
- imposing to `find_package()` to look for packages only in ***src***.

I don't know if there is a better solution that does not include the change of the package layout (I found that the correct package layout is a quite discussed topic), anyway we definitely must address this problem and a discussion around this is very welcome.

**Comment by fcatalan92** [comment]
Hi @pfecchio,
thank you for spotting this issue. Looking at the [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages) page that you linked, I found two alternatives that do not change the project structure:
```python
packages=find_packages(exclude=['tutorials', 'examples', 'tests'])
```
or
```python
packages=find_packages(include=['hipe4ml'])
```
I do not have a strong opinion on the structure changes. Maybe @mconcas knows better.

**Comment by mconcas** [comment]
Thanks @pfecchio and @fcatalan92 .

While I don't think this is a real problem, I agree for fixing it.
I personally like more with the first option presented by Fabio.
The reason is that we not planning, atm, to add other packages.
Adding a further level of directories is quite overkilling it.
It is nice to have the only installed package well visible at the first directory level in the repo.
This is my take, I might have overlooked some detail.

One last advice, pay a lot of attention with the `include` vs `exclude` logics.
Very often the combination of the two causes some headaches with unwanted behaviours (as a general truth).

**Comment by pfecchio** [comment]
Hi @fcatalan92 and @mconcas ,
thanks for your reply. I forgot to mention in the previous post that I already tried the solution @fcatalan92  suggest, but it doesn't work and this [issue](https://github.com/pypa/setuptools/issues/1571) in [setuptools](https://setuptools.readthedocs.io/en/latest/setuptools.html) explain why. 
Basically `find_package()` does not works as we expect it to.

I don't like to change the package layout too, but I can't find a different solution.

The reason why the installation from local source behaves differently from the one from [PyPi](https://pypi.org) remains unclear and @mconcas will investigate, if he will have time to do it.

**Comment by fcatalan92** [comment]
Hi @pfecchio, I saw that you closed PR #74.
It's fine for me to change the directory layout. Is there any reason to not do so?

**Comment by pfecchio** [comment]
Hi @fcatalan92, opening the PR was just an error. I thought I found a different solution that solved the problem without changing the package layout, so I opened the PR for this fix. But unfortunately that solution was not effective so I closed the PR.

For what concerns the directory layout, as far as I know it is not really important for Python packages, It's just a choice. So I think there are no problems with the **src/package** layout, but I could be wrong, if it's so please correct me! 

[Here](https://github.com/pypa/packaging.python.org/issues/320) there is a discussion (and in particular a [ comment](https://github.com/pypa/packaging.python.org/issues/320#issuecomment-495990983)) on this topic, you might find interesting.

**Comment by mconcas** [comment]
Is this still an open point?

**Comment by mconcas** [comment]
Closing as this is apparently not blocking anyone.
Feel free to refer this upon a PR fixing or in case it become a blocker.
