### ISSUE TITLE
Update XGBoost to 1.1.0

### ISSUE THREAD

**Issue by fcatalan92** [hipe4ml/hipe4ml#79]
Some times ago a [major release](https://github.com/dmlc/xgboost/releases/tag/v1.0.0) of XGBoost was released with a lot of improvements and changes. I think that now is a good time to move to the latest XGBoost release dmlc/xgboost#5337.
Moreover, an experimental model serialization in JSON has been added dmlc/xgboost#3980. This could be very useful to store models over a long time period.

### Limitations
- models trained with 0.90 could not be compatible with 1.1. A [conversion script is available]( https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html#loading-pickled-file-from-different-version-of-xgboost)
- when training parameter `reg_lambda` is set to zero, some leaf nodes may be assigned a NaN value. For now, please set `reg_lambda` to a nonzero value.

### Open points
- [x] to work with the new models, treelite need to be updated in the ALICE software at least to this commit https://github.com/dmlc/treelite/commit/6fd01e4f1890950bbcf9b124da24e886751bffe6
- [x] a fix in shap is pending release https://github.com/slundberg/shap/pull/1220

**Comment by mpuccio** [comment]
Treelite will be bumped with alisw/alidist#2285
