### ISSUE TITLE
Not inplace operations on TreeHandlers should return a new TreeHandler

### ISSUE THREAD

**Issue by fcatalan92** [hipe4ml/hipe4ml#82]
In my opinion, the TreeHandler methods that operate on the internal dataframe (such as: `apply_preselections`,  `shuffle_data_frame`, `eval_data_frame`) should return a new TreeHandler when `inplace=False`. Since, if you want a copy of the data after the operation, it is useful to keep also the handler structure and the dataframe is always accessible through `get_data_frame`.

**Comment by fmazzasc** [comment]
Hi Fabio, I agree with you. I can work on It next week

**Comment by mpuccio** [comment]
Fixed by #88
