### ISSUE TITLE
Same operations on full dataframe and slices

### ISSUE THREAD

**Issue by fcatalan92** [hipe4ml/hipe4ml#83]
It would be nice to have operations like `apply_preselections`, `get_subset`, `shuffle_data_frame`, `eval_data_frame` working also on the slices where present in the TreeHandler.

**Comment by fmazzasc** [comment]
Also here I agree with you. I can work on it next week, there are few things that need to be carefully implemented ( such as the seed/random_state setting) when dealing with slices. However is of course a functionality that we should add to the handler. Of course feel free to do that;)

**Comment by fcatalan92** [comment]
Maybe we can organize the work between ourself :-) They changes are quite substantial
