### ISSUE TITLE
Extend TreeHandler constructor to handle multiple files

### ISSUE THREAD

**Issue by fcatalan92** [hipe4ml/hipe4ml#84]
It could be interesting to be able to pass a list of files to the TreeHandler from which a "global" dataframe will be created.

**Comment by fmazzasc** [comment]
Yes, we are doing something similar for the hypertriton analysis @pfecchio . Uproot supports lists and also global patterns for local file paths using “*” . Check out this:

https://uproot.readthedocs.io/en/latest/opening-files.html#uproot-pandas-iterate
